### PR TITLE
pull base Khaled <- Master

### PR DESCRIPTION
**Pull request by glitcher255**

### CODE REVIEW

**Review by tufoinnkuo10 — COMMENTED** [review]
Hi @glitcher255 
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight

✅ gitignore ok



Required Changes ♻️
- [x] please  kindly change the  branch name from feature to something more descriptive, so that others can see what is being worked on
- [x] please , kindly use the updated readme template. you can find that [here](https://github.com/microverseinc/readme-template)

- [ ] please ensure that your Pull Request should have a descriptive title telling you what changes are inside eg Hello microverse project
- [ ] - [ ] please kindly add a pull request description. it will help a reviewer or viewer see what changes you made in the project. click on the 3dots and take edit to add your PR description.
Screenshot (629)_LI
- [ ] please kindly follow gitflow process and make your master branch the main branch. Pull Request is made from the feature branch into the main branch. you can check out more [here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).



Optional suggestions
- [ optional] please remember to always wait for a code reviewer to approve your project before you go ahead to merge your Pull Request. nice work
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by glitcher255** [comment]
Can you clarify on some of these points some more please? what would be a more descriptive title? I essentially copy pasted the readme example while adding any information that is relavent to the project, what am I missing here?

I renamed the master branch to main, is this correct?

Thank you

**Comment by medaminedev66** [comment]
Hello @glitcher255 👋,

_This is an additional review as a result of the second opinion request._

- This is your first project in Microverse and you are supposed to use GitHub flow, which means the Pull Request should be created from the feature branch into the main or master branch. This Pull Request is created from the master branch into the fracture-Khaled branch. I think you are not able to change the "feature-Khalid" branch to the master branch in the PR. I recommend opening a new PR from the "feature" branch into the "master" branch and adding the link of the old Pull request (this PR) to the description of the new PR. 
- Kindly ensure that the PR is open before requesting a new review. We only merge the PR after it has been approved
- Kindly implement the changes requested by the previous reviewer before requesting a new review.

Keep rocking 🚀!

**Comment by glitcher255** [comment]
Hey @medaminedev66 @tufoinnkkuo10 when attempting to pull from feature into master I am told that "there is nothing to compare" is there something I don't understand here? see screenshot

the otherway around does work as is what I did already, but seems to be wrong, what am I missing?

**Review by Qoosim — COMMENTED** [review]
#  *Status: Required Changes* :recycle:

Hi @glitcher255, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
-  Good README file. :heavy_check_mark: 
-  Descriptive PR summary. :heavy_check_mark: 




 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [ ] Kindly follow this [guide](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966) to change the base branch of your project. The pull request ought to be made from feature branch into the main branch. 
- [ ] Also, follow this [guide](https://bitbucket.org/blog/editing-pull-requests-just-got-a-little-easier) to change your pull request title to something like `Hello Microverse Project` instead of `main-clone(feature) pull request`.

**Comment by glitcher255** [comment]
@qoosim please check if this is correct https://github.com/glitcher255/stuff/pull/3

**Comment by Qoosim** [comment]
@glitcher255, correct :+1:

**Comment by glitcher255** [comment]
@Qoosim awesome! do I need to resubmit this? it says review pending, thank you!

**Pull request merged**
